### ISSUE TITLE
Q about COLMAP-Free 3DGS results

### ISSUE THREAD

**Issue by TwiceMao** [RaymondJiangkw/COGS#1]
Hello, @RaymondJiangkw  thank you for your excellent work! I have a question. The official code of the COLMAP-Free 3DGS paper does not seem to be open source yet. Did you reproduce the COLMAP-Free 3DGS code used in your paper yourself? If so, is it possible to share the code?

**Comment by RaymondJiangkw** [comment]
Well, thanks for your interest. If you notice, the part of authors of COLMAP-Free 3DGS are also authors of this paper... so, we run the experiment on the original code. If you want to get the code for COLMAP-Free 3DGS, maybe contacting the first-author of it would be better.
