### ISSUE TITLE
The training speed is very slow

### ISSUE THREAD

**Issue by WeihongPan** [RaymondJiangkw/COGS#11]
I trained on the Tanks/Family dataset on a single 3060Ti GPU with the command:
`python train.py -s ${source_path} --eval --num_images 100 -m ${model_path} --add_frame_interval 10 --register_steps 50 --align_steps 100 --iterations 30000`
as suggested in Readme-Tips for a relatively large number of training views. However, the training speed after alignment is unusually slow, taking nearly 10 hours to complete. Do you know if this is normal?

**Comment by RaymondJiangkw** [comment]
Hi, thanks for your interest. Unfortunately, it seems normal on 3060Ti… The second stage involves regular 3DGS optimization plus extra interleaved steps for optimizing camera parameters. However, the second stage uses the same rasterizer with the first stage which involves unnecessary approximate surface optimization. Therefore, the time consumption is sub-optimal.

We will try to speed things up, and it will also help if the algorithm runs on a faster card.
