### ISSUE TITLE
An error when estimating monocular depths

### ISSUE THREAD

**Issue by Riser6** [RaymondJiangkw/COGS#12]
Nice Work! But when I try to run the command to estimate monocular depth, an error is raising. 

OSError: Bingxin/Marigold does not appear to have a file named config.json.

I did install transformers==4.32.1 according to the requirements file. Can you give me any advice to solve it?

**Comment by RaymondJiangkw** [comment]
Can you also check whether your environment can run the official MariGold successfully?

Besides, it would be helpful if you could provide the stack trace along with the final error message. :)

**Comment by Riser6** [comment]
Many thanks for your reply! The error is that the pre-trained model of hugface cannot be loaded due to network reasons. I have solved this problem. Respect to your wonderful work!

**Comment by kk6398** [comment]
> Many thanks for your reply! The error is that the pre-trained model of hugface cannot be loaded due to network reasons. I have solved this problem. Respect to your wonderful work!

I meet the same issue. Can you give me some advice to solve it? My server can't connect to the vpn, so I can't connect to huggingface

**Comment by B-clover** [comment]
> > 非常感谢您的回复！错误是由于网络原因，无法加载 hugface 的预训练模型。我已经解决了这个问题。敬意您的出色工作！
> 
> 我遇到了同样的问题。您能给我一些解决它的建议吗？我的服务器无法连接到 VPN，因此无法连接到 huggingface

 HF_ENDPOINT="https://hf-mirror.com"

**Comment by B-clover** [comment]
> > Many thanks for your reply! The error is that the pre-trained model of hugface cannot be loaded due to network reasons. I have solved this problem. Respect to your wonderful work!
> 
> I meet the same issue. Can you give me some advice to solve it? My server can't connect to the vpn, so I can't connect to huggingface

 HF_ENDPOINT="https://hf-mirror.com"
