### ISSUE TITLE
Rendered depths seem weird in demo.ipynb

### ISSUE THREAD

**Issue by Master-cai** [RaymondJiangkw/COGS#2]
Thanks for your wonderful work!

When I running the demo.ipynb, the output rendered depths seem weird and different from the original output of the notebook. Any idea? Btw, I create a new envonment following your guidelines in cuda 12.1.

![image](https://github.com/RaymondJiangkw/COGS/assets/37432881/ea6f802b-05b7-4f88-bc88-2841ed944114)
![image](https://github.com/RaymondJiangkw/COGS/assets/37432881/d6c8a4d8-e1c0-4192-9ae2-f9e418950b1b)
![image](https://github.com/RaymondJiangkw/COGS/assets/37432881/1883b2bc-ea84-4199-9477-b66a603044dd)
![image](https://github.com/RaymondJiangkw/COGS/assets/37432881/03330771-7f2d-4d1a-8c62-1086be16f810)

Thank!

**Comment by RaymondJiangkw** [comment]
Thanks for your interest! This is because I change some code after writing the notebook and forget to update it… sorry for that.

The fix should be calling ‘set_up_scale_and_shift’ on every training camera as in the ‘train.py’ for initialization. I will update the notebook soon as well.

**Comment by RaymondJiangkw** [comment]
Should be fixed now.

**Comment by Master-cai** [comment]
@RaymondJiangkw  sorry to bother you again, I clone the latest code(09fb5a) again and reinstall the env, the depths seem normal but the rendered images are all black. 
![image](https://github.com/RaymondJiangkw/COGS/assets/37432881/3ab6c152-01e5-4126-856e-0a135a2dc3ee)
![image](https://github.com/RaymondJiangkw/COGS/assets/37432881/30287ad1-a175-461a-b873-47b116583757)
![image](https://github.com/RaymondJiangkw/COGS/assets/37432881/242ba558-b582-47a0-b14b-e2578d966760)
![image](https://github.com/RaymondJiangkw/COGS/assets/37432881/903dd8e8-ff53-4ff2-8296-4d2112aa07c1)

**Comment by RaymondJiangkw** [comment]
This is weird. Could you check the specific value of the rendered image? Also the value of rendered screen space coordinates. Since the depth shows up, the image should not be all black.

**Comment by Master-cai** [comment]
rendered image is all zeros
<img width="880" alt="image" src="https://github.com/RaymondJiangkw/COGS/assets/37432881/2318c2dd-66b0-44b0-9575-477e56c29689">
rendered screen space seems normal
<img width="985" alt="image" src="https://github.com/RaymondJiangkw/COGS/assets/37432881/eb9a2252-c538-4292-a644-ef9108662bdf">
@RaymondJiangkw

**Comment by RaymondJiangkw** [comment]
Since this problem does not show up in my system, I may need you to change some code for debugging... sorry for the inconvenience.

Could you change the line L476 in `submodules/diff-gaussian-rasterization-appr-surface/cuda_rasterizer/forward.cu` from `out_color[ch * H * W + pix_id] = C[ch] + T * bg_color[ch];` into `out_color[ch * H * W + pix_id] = T;`, and then reinstall the rasterizer and check the output of rendered image?

This is to check the remaining transmittance for the image rendering. If the results are close to 0, it then seems to be the color compute problem. If the results are close to 1, it is then very weird...

**Comment by Master-cai** [comment]
@RaymondJiangkw 
Thanks for your quick reply! I change the code and reinstalled the rasterizer, the image is still black.
<img width="971" alt="image" src="https://github.com/RaymondJiangkw/COGS/assets/37432881/2cc26870-6dda-4a49-bc4d-c9383ca92e45">

**Comment by RaymondJiangkw** [comment]
It means that the image rendering correctly aggregates the intersected gaussian kernels... but still I am also not sure why the radiance is zero. May I know your environment? like, which card are you using?

**Comment by Master-cai** [comment]
OS: Ubuntu 22.04.3 LTS, 
A100 gpu, cuda 12.1, 
Driver Version: 470.161.03

I only change the `pytorch-cuda=11.8` to `pytorch-cuda=12.1` in the `environment.yml`, others keeps un-changed.

It's really weird as in the first comment, the rendered image seems normal.
@RaymondJiangkw

**Comment by RaymondJiangkw** [comment]
Yes, indeed. I think I have similar environment, and I will test that.

**Comment by Master-cai** [comment]
@RaymondJiangkw 
Thank your so much! I export my conda env, hoping helpful for you to find the problem. Please ignore the `.txt` postfix.
[cogs.yml.txt](https://github.com/user-attachments/files/16048019/cogs.yml.txt)

**Comment by RaymondJiangkw** [comment]
Hi, sorry for the problem. Seems that the problem arises after I specify the newest `glm` in the rasterizer. If you check, you will see that the official gaussian splatting rasterizer also gives complete black images, and if you use `convert_SHs_to_color = True`, the images will show out.

The solution is to replace one line in the `forward.cu` for both rasterizers, which I have committed the changes. Please pull the changes and reinstall both rasterizers to see whether the problem still exists. Hopefully, there aren't additional bugs after specifying the newest `glm`...

If you encounter other problems, feel free to let me know!

**Comment by Master-cai** [comment]
Thanks! The rendering goes well now. 

I have another question. I'm wondering how can you initialize the first view so good, it seems you do not train the first view. And I think it's the cornerstone for the following optimization, since you compute matches based on the rendered image. In original gaussian splatting, even the colmap pose are given, it can not directly render such high quality image without training. I have read the supp and known that you initialize the scaling and the center of the gaussian ellipsoid to a computed value instead of the average distance between neighbors (proposed in vanilla gaussians). 

I want to ask what's the key success factor ? Can you introduce how to achieve such high quality initial rendering in more detail? Can it be applied to vanilla gaussians?

Thanks again! @RaymondJiangkw

**Comment by RaymondJiangkw** [comment]
Hi, this is simply the advantage given by the explicit primitives. It is also what ‘construct’ means in the title. :)

Since the gaussian kernels are explicit, we can simply construct a gaussian for each pixel, which guarantees that the rendered image and depth match with the provided rgb image and monocular depth.
