### ISSUE TITLE
The render result are completely black images

### ISSUE THREAD

**Issue by murmurelo111** [RaymondJiangkw/COGS#5]
Sorry to bother you, but I ran the following commands and got black images as the result:
```
python train.py -s Tanks/Museum --eval --num_images 6

python eval.py -m "output/2024-07-02_00-46-53_Museum_6/" --load_iteration 9000

python render.py -m "output/2024-07-02_00-46-53_Museum_6/" -s "COGS/Tanks/Museum/"
```
Could you please help me check what might be the problem? Thank you very much!
![image](https://github.com/RaymondJiangkw/COGS/assets/129838471/19290947-5a92-4ded-9986-d63e34781c67)

**Comment by murmurelo111** [comment]
```
python train.py -s "demo" --eval --num_images 2

python eval.py -m "COGS/output/2024-07-02_10-20-26_demo_2/"  --load_iteration 9000

python render.py -m "COGS/output/2024-07-02_10-20-26_demo_2/" -s "demo"
```
Even with the provided demo dataset, the result is still a completely black image.

**Comment by RaymondJiangkw** [comment]
Sure. I will look at it. Black images are indeed weird… I haven’t experienced that in my own experiments. Will check it soon.

**Comment by RaymondJiangkw** [comment]
Hi, sorry for the problem. Seems that the problem arises after I specify the newest `glm` in the rasterizer. If you check, you will see that the official gaussian splatting rasterizer also gives complete black images, and if you use `convert_SHs_to_color = True`, the images will show out.

The solution is to replace one line in the `forward.cu` for both rasterizers, which I have committed the changes. Please pull the changes and reinstall both rasterizers to see whether the problem still exists. Hopefully, there aren't additional bugs after specifying the newest `glm`...

If you encounter other problems, feel free to let me know!

**Comment by murmurelo111** [comment]
Thank you for your response! After pulling the changes, I got the correct results.
