### ISSUE TITLE
Custom DataSet

### ISSUE THREAD

**Issue by Z-zachary** [RaymondJiangkw/COGS#7]
First of all, thanks for your fantastic work!

I have some questions about custom dataset.
1. Can i train a weight for new scene,so that apply it on the other data in the scene.For example, i want to generator view for ocean.I want to first train the network using the ocean wave dataset that I have already used. I then used this network to generate new perspectives on my other ocean wave datasets.

2.Can the new viewpoints I generate control the camera pose? Can I get the camera pose for the generated new view?

**Comment by RaymondJiangkw** [comment]
Hi, thanks for your interest. I think I get what you mean.

After training a scene, you can of course do novel view synthesis by specifying the camera pose. Specifically, you could have a look at the evaluation code to have a sense of how to load a pre-trained model, and render it under a camera pose which is not seen in the training set.

Besides, for clarification, our model doesn't have a 'network', except for relying on some off-the-shelf models for pure inference.
