### ISSUE TITLE
How to remove the use of semantic_mask?

### ISSUE THREAD

**Issue by lu123456789** [RaymondJiangkw/COGS#8]
Hello, thank you for your excellent work. Could you please tell how to remove the use of semantic_mask? Thank you.

**Comment by RaymondJiangkw** [comment]
Hi, thanks for ur interest. Our method relies on the use of semantic masks. Not sure what u mean by the removal of use of semantic masks.

**Comment by lu123456789** [comment]
OK, thank you for your response. So, does this mean that the semantic_mask must be used? Is it possible to not use the semantic_mask?

**Comment by RaymondJiangkw** [comment]
Yes. The results will degrade in most cases without using semantic masks.

**Comment by lu123456789** [comment]
If the quality of the results is not considered, is there a switch in the program to enable or disable the use of semantic_mask?

**Comment by RaymondJiangkw** [comment]
yes, u can set `scale_and_shift_mode` to `whole` to avoid using semantic masks.

**Comment by lu123456789** [comment]
OK. Thank you very much.
